### ISSUE TITLE
malen respekterer ikke defaults for tabell- og figuroversikter 

### ISSUE THREAD

**Issue by sda030** [NIFU-NO/nifutypst#15]
Dersom man ikke har med følgende i YAML så får man feilmelding, til tross for at malen egentlig har default false.
```yaml
figure_table: false
table_table: false
```
For øvrig er vel Quarto/LaTeX-begrepene for disse lof og lot, men kanskje vanskelig å gjenbruke disse da Quarto presser vel inn sine, så blir det feilmelding om doble oppføringer.

**Comment by henrikkarlstrom** [comment]
Dette har nok med Quarto å gjøre, og ikke Henrik...
