### ISSUE TITLE
List Of Tables vises ikke

### ISSUE THREAD

**Issue by sda030** [NIFU-NO/nifutypst#21]

**Comment by henrikkarlstrom** [comment]
![bilde](https://github.com/NIFU-NO/nifutypst/assets/35686798/f947626d-e896-4b55-bd78-d0a41baf96cd)

Tenker du på noe annet enn dette?

**Comment by sda030** [comment]
Hm, jeg burde kanskje hatt et reprex.. Er ute nå men ganske sikker på at det var det jeg mente ja. Det fungerer nå fra quarto?

Noe litt på siden:
Eller så har en quarto sin egen yaml setting for lot og lof, men du måtte kanskje gjøre det på den måten for ikke at det kolliderer med det "innebygde"?

**Comment by henrikkarlstrom** [comment]
Her måtte det litt egenmekking til ja, men nå skal begge disse oversiktene fungere
