### ISSUE TITLE
Det skal ikke være så mye distanse mellom avsnittene

### ISSUE THREAD

**Issue by sda030** [NIFU-NO/nifutypst#22]
Sammenlign nifutypst-malen:
![image](https://github.com/NIFU-NO/nifutypst/assets/13221371/b1d1f9c8-0037-4cbd-b841-52f5d73d7489)

Med publisert rapport:
![image](https://github.com/NIFU-NO/nifutypst/assets/13221371/6ccbbcb4-8ded-4098-8638-e286e0b14bb6)

**Comment by henrikkarlstrom** [comment]
Fikset!
