### ISSUE TITLE
Tabell-caption må venstrejusteres og i fet tekst, er nå midtstilt og vanlig font

### ISSUE THREAD

**Issue by sda030** [NIFU-NO/nifutypst#24]
Skal være:
![image](https://github.com/NIFU-NO/nifutypst/assets/13221371/3e480f61-6775-4325-a1c9-3198c24609db)

nifutypst:
![image](https://github.com/NIFU-NO/nifutypst/assets/13221371/b309bef9-a890-41cd-90a8-d53a939a1302)

**Comment by henrikkarlstrom** [comment]
Fiksa!

![bilde](https://github.com/NIFU-NO/nifutypst/assets/35686798/16f2221b-a449-4b24-8e8f-10f13a5514d8)
