### ISSUE TITLE
Figur-caption må i fet skrift

### ISSUE THREAD

**Issue by sda030** [NIFU-NO/nifutypst#25]
Skal være: 
![image](https://github.com/NIFU-NO/nifutypst/assets/13221371/58a57e7c-9013-45ad-94e7-ddcd0b10f21f)

nifutypst:
![image](https://github.com/NIFU-NO/nifutypst/assets/13221371/9d34f396-f509-4081-b440-2ebc76120b84)

Merk at den er korrekt venstrejustert.

**Comment by henrikkarlstrom** [comment]
Fiksa!

![bilde](https://github.com/NIFU-NO/nifutypst/assets/35686798/d17d193f-f7fa-4e90-b9a9-f88bb2b54822)


(Jobber fortsatt med å få til riktig språk på bildetitler...)
