### ISSUE TITLE
nifu_pub til nifutypst

### ISSUE THREAD

**Issue by sda030** [NIFU-NO/nifutypst#27]
Litt forvirrende at utvidelsen (mappenavnet https://github.com/NIFU-NO/nifutypst/tree/main/_extensions/nifu_pub og https://github.com/NIFU-NO/nifutypst/blob/e67d90ffbb6d6d7bdaae00bb0ef84cf2a3802a8c/_extensions/nifu_pub/_extension.yml#L1) ikke har det samme navnet som github-repo. Kunne vi fått endret dette til nifutypst? Word-malen heter nifudocx både som github-repo og som utvidelse.

**Comment by henrikkarlstrom** [comment]
Mnja. Det spiller jo i det store bildet nesten ingen rolle hva ting heter, men jeg vil si det er en forskjell på "repoet for alt som har med Typst å gjøre" og den spesifikke malen det er snakk om her. Etter hvert kan det bli aktuelt å utvikle flere forskjellige Typst-maler (jeg har for eksempel en tanke om å lage en .typ-mal for preprints fra NIFU), og alle de kan bo i det samme repoet.

Quartos Typst-malverk har mange forskjellige extensions i samme repo: https://github.com/quarto-ext/typst-templates/tree/main
