### ISSUE TITLE
tabell- og figuroversikter som del av innholdsfortegnelsen

### ISSUE THREAD

**Issue by sda030** [NIFU-NO/nifutypst#5]
En NIFU-rapport har i realiteten tre innholdsfortegnelser (kalt outlines i .typ-språk) - en for elementene i rapporten, en for tabelloversikten og en for figurer. de to siste skal selv være elementer som fanges opp av den overordnete innholdsfortegnelsen, men det går ikke som outline-funksjonen er definert per nå. om vi vil ha det på plass tror jeg vi må fikle med query() i Typst,

**Comment by sda030** [comment]
Henrik: custom outline-funksjon som gjør det mulig å ha både tabell- og figuroversikter som outlines, som i seg selv blir referert i den overordnete innholdsfortegnelsen

**Comment by henrikkarlstrom** [comment]
Fikset!

![bilde](https://github.com/NIFU-NO/nifutypst/assets/35686798/2b933819-24a8-4b98-94dc-9a1cbf7d21c7)
